services:
  _defaults:
    public: true

  ##############
  # Your Module
  ldcodeeditor.module:
    class: ldcodeeditor
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ldcodeeditor'

  ldcodeeditor.context:
    class: Context
    factory: ['Context', 'getContext']

  #####################
  # PrestaShop Account
  ldcodeeditor.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.0'

  ldcodeeditor.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@ldcodeeditor.ps_accounts_installer'

  #####################
  # PrestaShop Billing

  ldcodeeditor.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
    - '@ldcodeeditor.ps_accounts_facade'
    - '@ldcodeeditor.context'

  ldcodeeditor.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
    - '@ldcodeeditor.ps_billings_context_wrapper'
    - '@ldcodeeditor.module'

  # Remove this if you do not need BillingService
  ldcodeeditor.ps_billings_service:
    class: 'PrestaShopCorp\Billing\Services\BillingService'
    public: true
    arguments:
    - '@ldcodeeditor.ps_billings_context_wrapper'
    - '@ldcodeeditor.module'